# Generated by Django 6.1 on 2026-09-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='phone',
        ),
    ]
